--[[

زخرفه سورس دوكس ✾
تم تعديل الملف واضافه الزخرفه بواسطه التركي (@HH22H)
#-------------------------------------------------------------------
]]

local function Khaleda(msg,MsgText)
if msg.type ~= "pv" then
if MsgText[1] == "زخرفه" then
redis:setex(matrex..":KhaledNow:"..msg.sender_user_id_,500,true)
sendMsg(msg.chat_id_,msg.id_,"| حسننا , الان يمكنك ارسال الاسم ولبعض الرموز المميزه اكتب رموز")    
return false
end

if redis:get(matrex..":KhaledNow:"..msg.sender_user_id_) then
redis:del(matrex..":KhaledNow:"..msg.sender_user_id_)
if utf8.len(msg.text) > 300 then
sendMsg(msg.chat_id_,msg.id_,"| لا يمكنك زخرفه اكثر من 20 حرف \n| ارسل امر زخرفه وحاول مجددا بحروف اقل")    
return false
elseif msg.text:match("\n") then
sendMsg(msg.chat_id_,msg.id_,"| لا يمكن زخرفه نص يحتوي على اكثر من سطر .")
return false
end
local EmojeS = {
' 𓁻',
' 𓏴  ',
' 𓏶 ',
' 𓏡',
' 𓏢', 
' 𓏣', 
' ☽‘',
' 𖠱²²', 
'▽', 
' 𖡛“', 
' 𖡚℡', 
' 𖡨', 
}

local Emoje = {
' ♕',
' 𖤍',
'˛𖤓',
' ཻ ☫',
' ♫ ',
' 𖠶 ',
' 𖠲',
' 𖡥',
'  ☬',
' 𖤐',
' 𓇼',
' ♘  '
}


local Khaled = Text:gsub('ض','ضِٰـِۢ')
Khaled = Khaled:gsub('ص','صِٰـِۢ')
Khaled = Khaled:gsub('ث','ثِٰـِۢ')
Khaled = Khaled:gsub('ق','قِٰـِۢ')
Khaled = Khaled:gsub('ف','فِٰ͒ـِۢ')
Khaled = Khaled:gsub('غ','غِٰـِۢ')
Khaled = Khaled:gsub('ع','عِٰـِۢ')
Khaled = Khaled:gsub('خ','خِٰ̐ـِۢ')
Khaled = Khaled:gsub('ح','حِٰـِۢ')
Khaled = Khaled:gsub('ج','جِٰـِۢ')
Khaled = Khaled:gsub('ش','شِٰـِۢ')
Khaled = Khaled:gsub('س','سِٰـِۢ')
Khaled = Khaled:gsub('ي','يِٰـِۢ')
Khaled = Khaled:gsub('ب','بِٰـِۢ')
Khaled = Khaled:gsub('ل','لِٰـِۢ')
Khaled = Khaled:gsub('ا','آ')
Khaled = Khaled:gsub('ت','تِٰـِۢ')
Khaled = Khaled:gsub('ن','نِٰـِۢ')
Khaled = Khaled:gsub('م','مِٰـِۢ')
Khaled = Khaled:gsub('ك','ڪِٰـِۢ')
Khaled = Khaled:gsub('ط','طِٰـِۢ')
Khaled = Khaled:gsub('ظ','ظِٰـِۢ')
Khaled = Khaled:gsub('ء','ء')
Khaled = Khaled:gsub('ؤ','ؤ')
Khaled = Khaled:gsub('ر','ر')
Khaled = Khaled:gsub('ى','ى')
Khaled = Khaled:gsub('ز','ز')
Khaled = Khaled:gsub('و','ﯛ̲୭')
Khaled = Khaled:gsub('ه','ۿۿہ')
Khaled = Khaled:gsub('a','𝗮')
Khaled = Khaled:gsub('A','𝗔')
Khaled = Khaled:gsub("b","𝗯")
Khaled = Khaled:gsub("B","𝗕")
Khaled = Khaled:gsub("c","𝗰")
Khaled = Khaled:gsub("C","𝗖")
Khaled = Khaled:gsub("d","𝗱")
Khaled = Khaled:gsub("D","𝗗")
Khaled = Khaled:gsub("e","𝗲")
Khaled = Khaled:gsub("E","𝗘")
Khaled = Khaled:gsub("f","𝗳")
Khaled = Khaled:gsub("F","𝗙")
Khaled = Khaled:gsub("g","𝗴")
Khaled = Khaled:gsub("G","𝗚")
Khaled = Khaled:gsub("h","𝗵")
Khaled = Khaled:gsub("H","𝗛")
Khaled = Khaled:gsub("i","𝗹")
Khaled = Khaled:gsub("I","𝗜")
Khaled = Khaled:gsub("j","𝗝")
Khaled = Khaled:gsub("J","𝗝")
Khaled = Khaled:gsub("k","𝗸")
Khaled = Khaled:gsub("K","𝗞")
Khaled = Khaled:gsub("l","𝗹")
Khaled = Khaled:gsub("L","𝗟")
Khaled = Khaled:gsub("m","𝗺")
Khaled = Khaled:gsub("M","𝗠")
Khaled = Khaled:gsub("n","𝗻")
Khaled = Khaled:gsub("N","𝗡")
Khaled = Khaled:gsub("o","𝗼")
Khaled = Khaled:gsub("O","𝗢")
Khaled = Khaled:gsub("p","𝗽")
Khaled = Khaled:gsub("P","𝗣")
Khaled = Khaled:gsub("q","𝗾")
Khaled = Khaled:gsub("Q","𝗤")
Khaled = Khaled:gsub("r","𝗿")
Khaled = Khaled:gsub("R","𝗥")
Khaled = Khaled:gsub("s","𝘀")
Khaled = Khaled:gsub("S","𝗦")
Khaled = Khaled:gsub("t","𝘁")
Khaled = Khaled:gsub("T","𝗧")
Khaled = Khaled:gsub("u","𝘂")
Khaled = Khaled:gsub("U","𝗨")
Khaled = Khaled:gsub("v","𝘃")
Khaled = Khaled:gsub("V","𝗩")
Khaled = Khaled:gsub("w","𝘄")
Khaled = Khaled:gsub("W","𝗪")
Khaled = Khaled:gsub("x","𝘅")
Khaled = Khaled:gsub("X","𝗫")
Khaled = Khaled:gsub("y","𝘆")
Khaled = Khaled:gsub("Y","𝗬")
Khaled = Khaled:gsub("z","𝘇")
Khaled = Khaled:gsub("Z","𝗭")



local Khaled2 = Text:gsub('ض','ضَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ص','صَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ث','ثَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ق','قَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ف','فَٰ͒ـُـٰٓ')
Khaled2 = Khaled2:gsub('غ','غَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ع','عَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('خ','خَٰ̐ـُـٰٓ')
Khaled2 = Khaled2:gsub('ح','حَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ج','جَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ش','شَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('س','سَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ي','يَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ب','بَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ل','لَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ا','آ')
Khaled2 = Khaled2:gsub('ت','تَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ن','نَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('م','مَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ك','ڪَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ط','طَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ظ','ظَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ء','ء')
Khaled2 = Khaled2:gsub('ؤ','ؤ')
Khaled2 = Khaled2:gsub('ر','ر')
Khaled2 = Khaled2:gsub('ى','ى')
Khaled2 = Khaled2:gsub('ز','ز')
Khaled2 = Khaled2:gsub('و','ﯛ̲୭')
Khaled2 = Khaled2:gsub("ه", "ۿۿہ")
Khaled2 = Khaled2:gsub('a',"𝖆")
Khaled2 = Khaled2:gsub('A',"𝖆")
Khaled2 = Khaled2:gsub("b","𝖇")
Khaled2 = Khaled2:gsub("B","𝖇")
Khaled2 = Khaled2:gsub("c","𝖈")
Khaled2 = Khaled2:gsub("C","𝖈")
Khaled2 = Khaled2:gsub("d","𝖉")
Khaled2 = Khaled2:gsub("D","𝖉")
Khaled2 = Khaled2:gsub("e","𝖊")
Khaled2 = Khaled2:gsub("E","𝖊")
Khaled2 = Khaled2:gsub("f","𝖋")
Khaled2 = Khaled2:gsub("F","𝖋")
Khaled2 = Khaled2:gsub("g","𝖌")
Khaled2 = Khaled2:gsub("G","𝖌")
Khaled2 = Khaled2:gsub("h","𝖍")
Khaled2 = Khaled2:gsub("H","𝖍")
Khaled2 = Khaled2:gsub("i","𝖎")
Khaled2 = Khaled2:gsub("I","𝖎")
Khaled2 = Khaled2:gsub("j","𝖏")
Khaled2 = Khaled2:gsub("J","𝖏")
Khaled2 = Khaled2:gsub("k","𝖐")
Khaled2 = Khaled2:gsub("K","𝖐")
Khaled2 = Khaled2:gsub("l","𝖑")
Khaled2 = Khaled2:gsub("L","𝖑")
Khaled2 = Khaled2:gsub("m","𝖒")
Khaled2 = Khaled2:gsub("M","𝖒")
Khaled2 = Khaled2:gsub("n","𝖓")
Khaled2 = Khaled2:gsub("N","𝖓")
Khaled2 = Khaled2:gsub("o","𝖔")
Khaled2 = Khaled2:gsub("O","𝖔")
Khaled2 = Khaled2:gsub("p","𝖕")
Khaled2 = Khaled2:gsub("P","𝖕")
Khaled2 = Khaled2:gsub("q","𝖖")
Khaled2 = Khaled2:gsub("Q","𝖖")
Khaled2 = Khaled2:gsub("r","𝖗")
Khaled2 = Khaled2:gsub("R","𝖗")
Khaled2 = Khaled2:gsub("s","𝖘")
Khaled2 = Khaled2:gsub("S","𝖘")
Khaled2 = Khaled2:gsub("t","𝖙")
Khaled2 = Khaled2:gsub("T","𝖙")
Khaled2 = Khaled2:gsub("u","𝖚")
Khaled2 = Khaled2:gsub("U","𝖚")
Khaled2 = Khaled2:gsub("v","𝖛")
Khaled2 = Khaled2:gsub("V","𝖛")
Khaled2 = Khaled2:gsub("w","𝖜")
Khaled2 = Khaled2:gsub("W","𝖜")
Khaled2 = Khaled2:gsub("x","𝖝")
Khaled2 = Khaled2:gsub("X","𝖝")
Khaled2 = Khaled2:gsub("y","𝖞")
Khaled2 = Khaled2:gsub("Y","𝖞")
Khaled2 = Khaled2:gsub("z","𝖟")
Khaled2 = Khaled2:gsub("Z","𝖟")


local Khaled3= Text:gsub('ض','ض')
Khaled3= Khaled3:gsub('ص','ص')
Khaled3= Khaled3:gsub('ث','ثہ')
Khaled3= Khaled3:gsub('ق','ق')
Khaled3= Khaled3:gsub('ف','فُہ')
Khaled3= Khaled3:gsub('غ','غہ')
Khaled3= Khaled3:gsub('ع','عہ')
Khaled3= Khaled3:gsub('ه','هٰہٰٖ')
Khaled3= Khaled3:gsub('خ','خہ')
Khaled3= Khaled3:gsub('ح','حہ')
Khaled3= Khaled3:gsub('ج','جہ')
Khaled3= Khaled3:gsub('د','د')
Khaled3= Khaled3:gsub('ذ','ذ')
Khaled3= Khaled3:gsub('ش','شہ')
Khaled3= Khaled3:gsub('س','سہ')
Khaled3= Khaled3:gsub('ي','يہ')
Khaled3= Khaled3:gsub('ب','بّ')
Khaled3= Khaled3:gsub('ل','لہ')
Khaled3= Khaled3:gsub('ا','ا')
Khaled3= Khaled3:gsub('ت','تہ')
Khaled3= Khaled3:gsub('ن','نٰہٰٖ')
Khaled3= Khaled3:gsub('م','مٰہٰٖ')
Khaled3= Khaled3:gsub('ك','كُہ')
Khaled3= Khaled3:gsub('ط','طہ')
Khaled3= Khaled3:gsub('ئ','ئ ْٰ')
Khaled3= Khaled3:gsub('ء','ء')
Khaled3= Khaled3:gsub('ؤ','ؤ')
Khaled3= Khaled3:gsub('ر','رَ')
Khaled3= Khaled3:gsub('لا','لہا')
Khaled3= Khaled3:gsub('ى','ىْ')
Khaled3= Khaled3:gsub('ة','ة')
Khaled3= Khaled3:gsub('و','و')
Khaled3= Khaled3:gsub('ز','ز')
Khaled3= Khaled3:gsub('ظ','ظۗہٰٰ')
Khaled3= Khaled3:gsub('q','𝐪')
Khaled3= Khaled3:gsub('Q','𝐪')
Khaled3= Khaled3:gsub('w','𝐰')
Khaled3= Khaled3:gsub('W','𝐰')
Khaled3= Khaled3:gsub('e','𝐞')
Khaled3= Khaled3:gsub('E','𝐞')
Khaled3= Khaled3:gsub('r','𝐫')
Khaled3= Khaled3:gsub('R','𝐫')
Khaled3= Khaled3:gsub('t','𝐭')
Khaled3= Khaled3:gsub('T','𝐭')
Khaled3= Khaled3:gsub('y','𝐲')
Khaled3= Khaled3:gsub('Y','𝐲')
Khaled3= Khaled3:gsub('u','𝐮')
Khaled3= Khaled3:gsub('i','𝐢')
Khaled3= Khaled3:gsub('o','𝐨')
Khaled3= Khaled3:gsub('p','𝐩')
Khaled3= Khaled3:gsub('a','𝐚')
Khaled3= Khaled3:gsub('s','𝐬')
Khaled3= Khaled3:gsub('d','𝐝')
Khaled3= Khaled3:gsub('f','𝐟')
Khaled3= Khaled3:gsub('g','𝐠')
Khaled3= Khaled3:gsub('h','𝐡')
Khaled3= Khaled3:gsub('j','𝐣')
Khaled3= Khaled3:gsub('k','𝐤')
Khaled3= Khaled3:gsub('U','𝐮')
Khaled3= Khaled3:gsub('I','𝐢')
Khaled3= Khaled3:gsub('O','𝐨')
Khaled3= Khaled3:gsub('P','𝐩')
Khaled3= Khaled3:gsub('A','𝐚')
Khaled3= Khaled3:gsub('S','𝐬')
Khaled3= Khaled3:gsub('D','𝐝')
Khaled3= Khaled3:gsub('F','𝐟')
Khaled3= Khaled3:gsub('G','𝐠')
Khaled3= Khaled3:gsub('H','𝐡')
Khaled3= Khaled3:gsub('J','𝐣')
Khaled3= Khaled3:gsub('K','𝐤')
Khaled3= Khaled3:gsub('L','𝐥')
Khaled3= Khaled3:gsub('l','𝐥')
Khaled3= Khaled3:gsub('z','𝐳')
Khaled3= Khaled3:gsub('Z','𝐳')
Khaled3= Khaled3:gsub('x','𝐱')
Khaled3= Khaled3:gsub('X','ẋ')
Khaled3= Khaled3:gsub('c','𝐜')
Khaled3= Khaled3:gsub('C','𝐜')
Khaled3= Khaled3:gsub('v','𝐯')
Khaled3= Khaled3:gsub('V','𝐯')
Khaled3= Khaled3:gsub('b','𝐛')
Khaled3= Khaled3:gsub('B','𝐛')
Khaled3= Khaled3:gsub('n','𝐧')
Khaled3= Khaled3:gsub('N','𝐧')
Khaled3= Khaled3:gsub('m','𝐦')
Khaled3= Khaled3:gsub('M','𝐦')


local Khaled4= Text:gsub('ض','ضۜہٰٰ')
Khaled4= Khaled4:gsub('ص','ضۜہٰٰ')
Khaled4= Khaled4:gsub('ث','ثہٰٰ')
Khaled4= Khaled4:gsub('ق','قྀ̲ہٰٰ')
Khaled4= Khaled4:gsub('ف','ف͒ہٰٰ')
Khaled4= Khaled4:gsub('غ','غہٰٰ')
Khaled4= Khaled4:gsub('ع','عہٰٰ')
Khaled4= Khaled4:gsub('ه','هٰہٰٖ')
Khaled4= Khaled4:gsub('خ','خٰ̐ہ ')
Khaled4= Khaled4:gsub('ح','حہٰٰ')
Khaled4= Khaled4:gsub('ج','جـٰ̲ـہْۧ')
Khaled4= Khaled4:gsub('د','دٰ')
Khaled4= Khaled4:gsub('ذ','ذِٰ')
Khaled4= Khaled4:gsub('ش','شِٰہٰٰ')
Khaled4= Khaled4:gsub('س','سٰٓ')
Khaled4= Khaled4:gsub('ي','يِٰہ')
Khaled4= Khaled4:gsub('ب','بّہ')
Khaled4= Khaled4:gsub('ل','لـٰ̲ـہ')
Khaled4= Khaled4:gsub('ا','آ')
Khaled4= Khaled4:gsub('ت','تَہَٰ')
Khaled4= Khaled4:gsub('ن','نَِہ')
Khaled4= Khaled4:gsub('م','مٰ̲ہ')
Khaled4= Khaled4:gsub('ك','ڪٰྀہٰٰ')
Khaled4= Khaled4:gsub('ط','طۨہٰٰ')
Khaled4= Khaled4:gsub('ئ','ئ ْٰ')
Khaled4= Khaled4:gsub('ء','ء')
Khaled4= Khaled4:gsub('ؤ','ؤ')
Khaled4= Khaled4:gsub('ر','رَ')
Khaled4= Khaled4:gsub('لا','لہا')
Khaled4= Khaled4:gsub('ى','ىْ')
Khaled4= Khaled4:gsub('ة','ة')
Khaled4= Khaled4:gsub('و','وِٰ')
Khaled4= Khaled4:gsub('ز','زَٰ')
Khaled4= Khaled4:gsub('ظ','ظۗہٰٰ')
Khaled4= Khaled4:gsub('q','𝑸')
Khaled4= Khaled4:gsub('Q','𝑸')
Khaled4= Khaled4:gsub('w','𝑾')
Khaled4= Khaled4:gsub('W','𝑾')
Khaled4= Khaled4:gsub('e','𝑬')
Khaled4= Khaled4:gsub('E','𝑬')
Khaled4= Khaled4:gsub('r','𝑹')
Khaled4= Khaled4:gsub('R','𝑹')
Khaled4= Khaled4:gsub('t','𝑻')
Khaled4= Khaled4:gsub('T','𝑻')
Khaled4= Khaled4:gsub('y','𝒀')
Khaled4= Khaled4:gsub('Y','𝒀')
Khaled4= Khaled4:gsub('u','𝑼')
Khaled4= Khaled4:gsub('U','𝑼')
Khaled4= Khaled4:gsub('i','𝑰')
Khaled4= Khaled4:gsub('I','𝑰')
Khaled4= Khaled4:gsub('o','𝑶')
Khaled4= Khaled4:gsub('O','𝑶')
Khaled4= Khaled4:gsub('p','𝑷')
Khaled4= Khaled4:gsub('P','𝑷')
Khaled4= Khaled4:gsub('a','𝑨')
Khaled4= Khaled4:gsub('A','𝑨')
Khaled4= Khaled4:gsub('s','𝑺')
Khaled4= Khaled4:gsub('S','𝑺')
Khaled4= Khaled4:gsub('d','𝑫')
Khaled4= Khaled4:gsub('D','𝑫')
Khaled4= Khaled4:gsub('f','𝑭')
Khaled4= Khaled4:gsub('F','𝑭')
Khaled4= Khaled4:gsub('g','𝑮')
Khaled4= Khaled4:gsub('G','𝑮')
Khaled4= Khaled4:gsub('h','𝑯')
Khaled4= Khaled4:gsub('H','𝑯')
Khaled4= Khaled4:gsub('j','𝑱')
Khaled4= Khaled4:gsub('J','𝑱')
Khaled4= Khaled4:gsub('k','𝑲')
Khaled4= Khaled4:gsub('K','𝑲')
Khaled4= Khaled4:gsub('l','𝑳')
Khaled4= Khaled4:gsub('L','𝑳')
Khaled4= Khaled4:gsub('z','𝒁')
Khaled4= Khaled4:gsub('Z','𝒁')
Khaled4= Khaled4:gsub('x','𝑿')
Khaled4= Khaled4:gsub('X','𝑿')
Khaled4= Khaled4:gsub('c','𝑪')
Khaled4= Khaled4:gsub('C','𝑪')
Khaled4= Khaled4:gsub('v','𝑽')
Khaled4= Khaled4:gsub('V','𝑽')
Khaled4= Khaled4:gsub('b','𝑩')
Khaled4= Khaled4:gsub('B','𝑩')
Khaled4= Khaled4:gsub('n','𝑵')
Khaled4= Khaled4:gsub('N','𝑵')
Khaled4= Khaled4:gsub('m','𝑴')
Khaled4= Khaled4:gsub('M','𝑴')



local Khaled5= Text:gsub('ض','ضَ')
Khaled5= Khaled5:gsub('ص','صً')
Khaled5= Khaled5:gsub('ث','ثَ')
Khaled5= Khaled5:gsub('ق','قُ')
Khaled5= Khaled5:gsub('ف','فّ')
Khaled5= Khaled5:gsub('غ','غِ')
Khaled5= Khaled5:gsub('ع','عُ')
Khaled5= Khaled5:gsub('ه','ﮭ')
Khaled5= Khaled5:gsub('خ','خِ')
Khaled5= Khaled5:gsub('ح','حٌ')
Khaled5= Khaled5:gsub('ج','جُ')
Khaled5= Khaled5:gsub('د','دِ')
Khaled5= Khaled5:gsub('ذ','ذَ')
Khaled5= Khaled5:gsub('ش','شِ')
Khaled5= Khaled5:gsub('س','سً')
Khaled5= Khaled5:gsub('ي','يْ')
Khaled5= Khaled5:gsub('ب','بّ')
Khaled5= Khaled5:gsub('ل','لَ')
Khaled5= Khaled5:gsub('ا','أُ')
Khaled5= Khaled5:gsub('ت','تٌ')
Khaled5= Khaled5:gsub('ن','نً')
Khaled5= Khaled5:gsub('م','مِ')
Khaled5= Khaled5:gsub('ك','ڳّ')
Khaled5= Khaled5:gsub('ط','طٌ')
Khaled5= Khaled5:gsub('ئ','ئ')
Khaled5= Khaled5:gsub('ء','ء')
Khaled5= Khaled5:gsub('ؤ','ؤ')
Khaled5= Khaled5:gsub('ر','رٌ')
Khaled5= Khaled5:gsub('لا','لٌأً')
Khaled5= Khaled5:gsub('ى','ى')
Khaled5= Khaled5:gsub('ة','ةَ')
Khaled5= Khaled5:gsub('و','وِ')
Khaled5= Khaled5:gsub('ز','زُ')
Khaled5= Khaled5:gsub('ظ','ظ')
Khaled5= Khaled5:gsub('q','𝒒')
Khaled5= Khaled5:gsub('Q','𝒒')
Khaled5= Khaled5:gsub('w','𝒘')
Khaled5= Khaled5:gsub('W','𝒘')
Khaled5= Khaled5:gsub('e','𝒆')
Khaled5= Khaled5:gsub('E','𝒆')
Khaled5= Khaled5:gsub('r','𝒓')
Khaled5= Khaled5:gsub('R','𝒓')
Khaled5= Khaled5:gsub('t','𝒕')
Khaled5= Khaled5:gsub('T','𝒕')
Khaled5= Khaled5:gsub('y','𝒚')
Khaled5= Khaled5:gsub('Y','𝒚')
Khaled5= Khaled5:gsub('u','𝒖')
Khaled5= Khaled5:gsub('U','𝒖')
Khaled5= Khaled5:gsub('i','𝒊')
Khaled5= Khaled5:gsub('I','𝒊')
Khaled5= Khaled5:gsub('o','𝒐')
Khaled5= Khaled5:gsub('O','𝒐')
Khaled5= Khaled5:gsub('p','𝒑')
Khaled5= Khaled5:gsub('P','𝒑')
Khaled5= Khaled5:gsub('a','𝒂')
Khaled5= Khaled5:gsub('A','𝒂')
Khaled5= Khaled5:gsub('s','𝒔')
Khaled5= Khaled5:gsub('S','𝒔')
Khaled5= Khaled5:gsub('d','𝒅')
Khaled5= Khaled5:gsub('D','𝒅')
Khaled5= Khaled5:gsub('f','𝒇')
Khaled5= Khaled5:gsub('F','𝒇')
Khaled5= Khaled5:gsub('g','𝒈')
Khaled5= Khaled5:gsub('G','𝒈')
Khaled5= Khaled5:gsub('h','𝒉')
Khaled5= Khaled5:gsub('H','𝒉')
Khaled5= Khaled5:gsub('j','𝒋')
Khaled5= Khaled5:gsub('J','𝒋')
Khaled5= Khaled5:gsub('K','𝒌')
Khaled5= Khaled5:gsub('k','𝒌')
Khaled5= Khaled5:gsub('L','𝒍')
Khaled5= Khaled5:gsub('l','𝒍')
Khaled5= Khaled5:gsub('z','𝒛')
Khaled5= Khaled5:gsub('Z','𝒛')
Khaled5= Khaled5:gsub('x','𝒙')
Khaled5= Khaled5:gsub('X','𝒙')
Khaled5= Khaled5:gsub('c','𝒄')
Khaled5= Khaled5:gsub('C','𝒄')
Khaled5= Khaled5:gsub('v','𝒗')
Khaled5= Khaled5:gsub('V','𝒗')
Khaled5= Khaled5:gsub('b','𝒃')
Khaled5= Khaled5:gsub('B','𝒃')
Khaled5= Khaled5:gsub('n','𝒏')
Khaled5= Khaled5:gsub('N','𝒏')
Khaled5= Khaled5:gsub('m','𝒎')
Khaled5= Khaled5:gsub('M','𝒎')



local Khaled6= Text:gsub('ض','ﺿ̭͠')
Khaled6= Khaled6:gsub('ص','ﺻ͡')
Khaled6= Khaled6:gsub('ث','ﺜ̲')
Khaled6= Khaled6:gsub('ق','ﭰ')
Khaled6= Khaled6:gsub('ف','ﻓ̲')
Khaled6= Khaled6:gsub('غ','ﻏ̲')
Khaled6= Khaled6:gsub('ع','ﻌ̲')
Khaled6= Khaled6:gsub('ه','ﮬ̲̌')
Khaled6= Khaled6:gsub('خ','خٌ')
Khaled6= Khaled6:gsub('ح','ﺣ̅')
Khaled6= Khaled6:gsub('ج','جُ')
Khaled6= Khaled6:gsub('د','ډ̝')
Khaled6= Khaled6:gsub('ذ','ذً')
Khaled6= Khaled6:gsub('ش','ﺷ̲')
Khaled6= Khaled6:gsub('س','ﺳ̉')
Khaled6= Khaled6:gsub('ي','ﯾ̃̐')
Khaled6= Khaled6:gsub('ب','ﺑ̲')
Khaled6= Khaled6:gsub('ل','ا̄ﻟ')
Khaled6= Khaled6:gsub('ا','ﺈ̃')
Khaled6= Khaled6:gsub('ت','ټُ')
Khaled6= Khaled6:gsub('ن','ﻧ̲')
Khaled6= Khaled6:gsub('م','ﻣ̲̉')
Khaled6= Khaled6:gsub('ك','گ')
Khaled6= Khaled6:gsub('ط','ﻁ̲')
Khaled6= Khaled6:gsub('ئ',' ْٰئ')
Khaled6= Khaled6:gsub('ء','ء')
Khaled6= Khaled6:gsub('ؤ','ؤ')
Khaled6= Khaled6:gsub('ر','ہڕ')
Khaled6= Khaled6:gsub('لا','ﻟ̲ﺂ̲')
Khaled6= Khaled6:gsub('ى','ى')
Khaled6= Khaled6:gsub('ة','ة')
Khaled6= Khaled6:gsub('و','ۇۈۉ')
Khaled6= Khaled6:gsub('ز','زُ')
Khaled6= Khaled6:gsub('ظ','ﻇ̲')
Khaled6= Khaled6:gsub('q','ǫ')
Khaled6= Khaled6:gsub('Q','ǫ')
Khaled6= Khaled6:gsub('w','ᴡ')
Khaled6= Khaled6:gsub('W','ᴡ')
Khaled6= Khaled6:gsub('e','ᴇ')
Khaled6= Khaled6:gsub('E','ᴇ')
Khaled6= Khaled6:gsub('r','ʀ')
Khaled6= Khaled6:gsub('R','ʀ')
Khaled6= Khaled6:gsub('t','ᴛ')
Khaled6= Khaled6:gsub('T','ᴛ')
Khaled6= Khaled6:gsub('y','ʏ')
Khaled6= Khaled6:gsub('Y','ʏ')
Khaled6= Khaled6:gsub('u','ụ')
Khaled6= Khaled6:gsub('U','ụ')
Khaled6= Khaled6:gsub('i','ɪ')
Khaled6= Khaled6:gsub('I','ɪ')
Khaled6= Khaled6:gsub('o','ᴏ')
Khaled6= Khaled6:gsub('O','ᴏ')
Khaled6= Khaled6:gsub('p','ᴘ')
Khaled6= Khaled6:gsub('P','ᴘ')
Khaled6= Khaled6:gsub('a','ᴀ')
Khaled6= Khaled6:gsub('A','ᴀ')
Khaled6= Khaled6:gsub('s','ѕ')
Khaled6= Khaled6:gsub('S','ѕ')
Khaled6= Khaled6:gsub('d','ᴅ')
Khaled6= Khaled6:gsub('D','ᴅ')
Khaled6= Khaled6:gsub('f','ғ')
Khaled6= Khaled6:gsub('F','ғ')
Khaled6= Khaled6:gsub('g','ɢ')
Khaled6= Khaled6:gsub('G','ɢ')
Khaled6= Khaled6:gsub('h','ʜ')
Khaled6= Khaled6:gsub('H','ʜ')
Khaled6= Khaled6:gsub('j','ᴊ')
Khaled6= Khaled6:gsub('J','ᴊ')
Khaled6= Khaled6:gsub('K','ᴋ')
Khaled6= Khaled6:gsub('k','ᴋ')
Khaled6= Khaled6:gsub('L','ʟ')
Khaled6= Khaled6:gsub('l','ʟ')
Khaled6= Khaled6:gsub('z','ᴢ')
Khaled6= Khaled6:gsub('Z','ᴢ')
Khaled6= Khaled6:gsub('x','х')
Khaled6= Khaled6:gsub('X','х')
Khaled6= Khaled6:gsub('c','ᴄ')
Khaled6= Khaled6:gsub('C','ᴄ')
Khaled6= Khaled6:gsub('v','ᴠ')
Khaled6= Khaled6:gsub('V','ᴠ')
Khaled6= Khaled6:gsub('b','ʙ')
Khaled6= Khaled6:gsub('B','ʙ')
Khaled6= Khaled6:gsub('n','ɴ')
Khaled6= Khaled6:gsub('N','ɴ')
Khaled6= Khaled6:gsub('m','ᴍ')
Khaled6= Khaled6:gsub('M','ᴍ')



local Khaled7= Text:gsub('ض','ﺿ')
Khaled7= Khaled7:gsub('ص','ﺻ')
Khaled7= Khaled7:gsub('ث','ﭥ')
Khaled7= Khaled7:gsub('ق','ﻗ̮ـ̃')
Khaled7= Khaled7:gsub('ف','ﭬ')
Khaled7= Khaled7:gsub('غ','ﻏ̣̐')
Khaled7= Khaled7:gsub('ع','ﻋ')
Khaled7= Khaled7:gsub('ه','ھَہّ')
Khaled7= Khaled7:gsub('خ','ﺧ')
Khaled7= Khaled7:gsub('ح','פ')
Khaled7= Khaled7:gsub('ج','ﭴ')
Khaled7= Khaled7:gsub('د','ﮃ')
Khaled7= Khaled7:gsub('ذ','ذ')
Khaled7= Khaled7:gsub('ش','ﺷ')
Khaled7= Khaled7:gsub('س','ﺳ')
Khaled7= Khaled7:gsub('ي','ﯾ')
Khaled7= Khaled7:gsub('ب','ﺑ')
Khaled7= Khaled7:gsub('ل','ﻟ')
Khaled7= Khaled7:gsub('ا','ﺂ')
Khaled7= Khaled7:gsub('ت','ﭠ')
Khaled7= Khaled7:gsub('ن','ﻧ')
Khaled7= Khaled7:gsub('م','ﻣ̝̚')
Khaled7= Khaled7:gsub('ك','گـ')
Khaled7= Khaled7:gsub('ط','ﻁْ')
Khaled7= Khaled7:gsub('ئ','ٰئـ')
Khaled7= Khaled7:gsub('ء','ء')
Khaled7= Khaled7:gsub('ؤ','ﯗ')
Khaled7= Khaled7:gsub('ر','ړُ')
Khaled7= Khaled7:gsub('لا','ﻟآ')
Khaled7= Khaled7:gsub('ى','ـﮯ')
Khaled7= Khaled7:gsub('ة','ة')
Khaled7= Khaled7:gsub('و','ۆ')
Khaled7= Khaled7:gsub('ز','ژ')
Khaled7= Khaled7:gsub('ظ','ﻅ')
Khaled7= Khaled7:gsub('q','𝘘')
Khaled7= Khaled7:gsub('Q','𝘘')
Khaled7= Khaled7:gsub('w','𝘞')
Khaled7= Khaled7:gsub('W','𝘞')
Khaled7= Khaled7:gsub('e','𝘌')
Khaled7= Khaled7:gsub('E','𝘌')
Khaled7= Khaled7:gsub('r','𝘙')
Khaled7= Khaled7:gsub('R','𝘙')
Khaled7= Khaled7:gsub('t','𝘛')
Khaled7= Khaled7:gsub('T','𝘛')
Khaled7= Khaled7:gsub('y','𝘠')
Khaled7= Khaled7:gsub('Y','𝘠')
Khaled7= Khaled7:gsub('u','𝘜')
Khaled7= Khaled7:gsub('U','𝘜')
Khaled7= Khaled7:gsub('i','𝘐')
Khaled7= Khaled7:gsub('I','𝘐')
Khaled7= Khaled7:gsub('o','𝘖')
Khaled7= Khaled7:gsub('O','𝘖')
Khaled7= Khaled7:gsub('p','𝘗')
Khaled7= Khaled7:gsub('P','𝘗')
Khaled7= Khaled7:gsub('a','𝘈')
Khaled7= Khaled7:gsub('A','𝘈')
Khaled7= Khaled7:gsub('s','𝘚')
Khaled7= Khaled7:gsub('S','𝘚')
Khaled7= Khaled7:gsub('d','𝘋')
Khaled7= Khaled7:gsub('D','𝘋')
Khaled7= Khaled7:gsub('f','𝘍')
Khaled7= Khaled7:gsub('F','𝘍')
Khaled7= Khaled7:gsub('g','𝘎')
Khaled7= Khaled7:gsub('G','𝘎')
Khaled7= Khaled7:gsub('h','𝘏')
Khaled7= Khaled7:gsub('H','𝘏')
Khaled7= Khaled7:gsub('j','𝘑')
Khaled7= Khaled7:gsub('J','𝘑')
Khaled7= Khaled7:gsub('k','𝘒')
Khaled7= Khaled7:gsub('K','𝘒')
Khaled7= Khaled7:gsub('L','𝘓')
Khaled7= Khaled7:gsub('l','𝘓')
Khaled7= Khaled7:gsub('z','𝘡')
Khaled7= Khaled7:gsub('Z','𝘡')
Khaled7= Khaled7:gsub('x','𝘟')
Khaled7= Khaled7:gsub('X','𝘟')
Khaled7= Khaled7:gsub('c','𝘊')
Khaled7= Khaled7:gsub('C','𝘊')
Khaled7= Khaled7:gsub('v','𝘝')
Khaled7= Khaled7:gsub('V','𝘝')
Khaled7= Khaled7:gsub('b','𝘉')
Khaled7= Khaled7:gsub('B','𝘉')
Khaled7= Khaled7:gsub('n','𝘕')
Khaled7= Khaled7:gsub('N','𝘕')
Khaled7= Khaled7:gsub('m','𝘔')
Khaled7= Khaled7:gsub('M','𝘔')



local Khaled8= Text:gsub('ض','ض');
Khaled8= Khaled8:gsub('ص','صہٰ')
Khaled8= Khaled8:gsub('ث','ثہٰـ')
Khaled8= Khaled8:gsub('ق','قہٰ')
Khaled8= Khaled8:gsub('ف','فہٰ')
Khaled8= Khaled8:gsub('غ','غـْ')
Khaled8= Khaled8:gsub('ع','ع')
Khaled8= Khaled8:gsub('ه','هٰہٰٖ')
Khaled8= Khaled8:gsub('خ','خخَـ')
Khaled8= Khaled8:gsub('ح','حہٰ')
Khaled8= Khaled8:gsub('ج','ججہٰ')
Khaled8= Khaled8:gsub('د','دَ')
Khaled8= Khaled8:gsub('ذ','ذّ')
Khaled8= Khaled8:gsub('ش','ششہٰ')
Khaled8= Khaled8:gsub('س','سہٰ')
Khaled8= Khaled8:gsub('ي','يٰ')
Khaled8= Khaled8:gsub('ب','بٰٰ')
Khaled8= Khaled8:gsub('ل','لہٰ')
Khaled8= Khaled8:gsub('ا','آ')
Khaled8= Khaled8:gsub('ت','تہٰ')
Khaled8= Khaled8:gsub('ن','نہٰ')
Khaled8= Khaled8:gsub('م','مہٰ')
Khaled8= Khaled8:gsub('ك','ككہٰ')
Khaled8= Khaled8:gsub('ط','طہٰ')
Khaled8= Khaled8:gsub('ئ',' ْئٰ')
Khaled8= Khaled8:gsub('ء','ء')
Khaled8= Khaled8:gsub('ؤ','ؤؤَ')
Khaled8= Khaled8:gsub('ر','رَ')
Khaled8= Khaled8:gsub('لا','لہٰا')
Khaled8= Khaled8:gsub('ى','ىہٰ')
Khaled8= Khaled8:gsub('ة','ة')
Khaled8= Khaled8:gsub('و','ہٰو')
Khaled8= Khaled8:gsub('ز','ز')
Khaled8= Khaled8:gsub('ظ','ظہٰ')
Khaled8= Khaled8:gsub('q','𝚀')
Khaled8= Khaled8:gsub('Q','𝚀')
Khaled8= Khaled8:gsub('w','𝚆')
Khaled8= Khaled8:gsub('W','𝚆')
Khaled8= Khaled8:gsub('e','𝙴')
Khaled8= Khaled8:gsub('E','𝙴')
Khaled8= Khaled8:gsub('r','𝚁')
Khaled8= Khaled8:gsub('R','𝚁')
Khaled8= Khaled8:gsub('t','𝚃')
Khaled8= Khaled8:gsub('T','𝚃')
Khaled8= Khaled8:gsub('y','𝚈')
Khaled8= Khaled8:gsub('Y','𝚈')
Khaled8= Khaled8:gsub('u','𝚄')
Khaled8= Khaled8:gsub('U','𝚄')
Khaled8= Khaled8:gsub('i','𝙸')
Khaled8= Khaled8:gsub('I','𝙸')
Khaled8= Khaled8:gsub('o','𝙾')
Khaled8= Khaled8:gsub('O','𝙾')
Khaled8= Khaled8:gsub('p','𝙿')
Khaled8= Khaled8:gsub('P','𝙿')
Khaled8= Khaled8:gsub('a','𝙰')
Khaled8= Khaled8:gsub('A','𝙰')
Khaled8= Khaled8:gsub('s','𝚂')
Khaled8= Khaled8:gsub('S','𝚂')
Khaled8= Khaled8:gsub('d','𝙳')
Khaled8= Khaled8:gsub('D','𝙳')
Khaled8= Khaled8:gsub('f','𝙵')
Khaled8= Khaled8:gsub('F','𝙵')
Khaled8= Khaled8:gsub('g','𝙶')
Khaled8= Khaled8:gsub('G','𝙶')
Khaled8= Khaled8:gsub('h','𝙷')
Khaled8= Khaled8:gsub('H','𝙷')
Khaled8= Khaled8:gsub('j','𝙹')
Khaled8= Khaled8:gsub('J','𝙹')
Khaled8= Khaled8:gsub('k','𝙺')
Khaled8= Khaled8:gsub('K','𝙺')
Khaled8= Khaled8:gsub('L','𝙻')
Khaled8= Khaled8:gsub('l','𝙻')
Khaled8= Khaled8:gsub('z','𝚉')
Khaled8= Khaled8:gsub('Z','𝚉')
Khaled8= Khaled8:gsub('x','𝚇')
Khaled8= Khaled8:gsub('X','𝚇')
Khaled8= Khaled8:gsub('c','𝙲')
Khaled8= Khaled8:gsub('C','𝙲')
Khaled8= Khaled8:gsub('v','𝚅')
Khaled8= Khaled8:gsub('V','𝚅')
Khaled8= Khaled8:gsub('b','𝙱')
Khaled8= Khaled8:gsub('B','𝙱')
Khaled8= Khaled8:gsub('n','𝙽')
Khaled8= Khaled8:gsub('N','𝙽')
Khaled8= Khaled8:gsub('m','𝙼')
Khaled8= Khaled8:gsub('M','𝙼')



local Khaled9= Text:gsub('ض','ض')
Khaled9= Khaled9:gsub('ص','ص')
Khaled9= Khaled9:gsub('ث','ث')
Khaled9= Khaled9:gsub('ق','قٌ')
Khaled9= Khaled9:gsub('ف','فُ')
Khaled9= Khaled9:gsub('غ','غ')
Khaled9= Khaled9:gsub('ع','عٍ')
Khaled9= Khaled9:gsub('ه','هـ')
Khaled9= Khaled9:gsub('خ','خـ')
Khaled9= Khaled9:gsub('ح','حٍ')
Khaled9= Khaled9:gsub('ج','جٍ')
Khaled9= Khaled9:gsub('د','دِ')
Khaled9= Khaled9:gsub('ذ','ذَ')
Khaled9= Khaled9:gsub('ش','شُ')
Khaled9= Khaled9:gsub('س','س')
Khaled9= Khaled9:gsub('ي','ي')
Khaled9= Khaled9:gsub('ب','بَ')
Khaled9= Khaled9:gsub('ل','لُِ')
Khaled9= Khaled9:gsub('ا','آ')
Khaled9= Khaled9:gsub('ت','ت')
Khaled9= Khaled9:gsub('ن','ن')
Khaled9= Khaled9:gsub('م','م')
Khaled9= Khaled9:gsub('ك','ڪ')
Khaled9= Khaled9:gsub('ط','طُ')
Khaled9= Khaled9:gsub('ئ','ئ ْٰ')
Khaled9= Khaled9:gsub('ء','ء')
Khaled9= Khaled9:gsub('ؤ','ؤ')
Khaled9= Khaled9:gsub('ر','ر')
Khaled9= Khaled9:gsub('لا','لُِآ')
Khaled9= Khaled9:gsub('ى','ىْ')
Khaled9= Khaled9:gsub('ة','ة')
Khaled9= Khaled9:gsub('و','وو')
Khaled9= Khaled9:gsub('ز','ز')
Khaled9= Khaled9:gsub('ظ','ظهُ')
Khaled9= Khaled9:gsub('q','ℚ')
Khaled9= Khaled9:gsub('Q','ℚ')
Khaled9= Khaled9:gsub('w','𝕎')
Khaled9= Khaled9:gsub('W','𝕎')
Khaled9= Khaled9:gsub('e','𝔼')
Khaled9= Khaled9:gsub('E','𝔼')
Khaled9= Khaled9:gsub('r','ℝ')
Khaled9= Khaled9:gsub('R','ℝ')
Khaled9= Khaled9:gsub('t','𝕋')
Khaled9= Khaled9:gsub('T','𝕋')
Khaled9= Khaled9:gsub('y','𝕐')
Khaled9= Khaled9:gsub('Y','𝕐')
Khaled9= Khaled9:gsub('u','𝕌')
Khaled9= Khaled9:gsub('U','𝕌')
Khaled9= Khaled9:gsub('i','𝕀')
Khaled9= Khaled9:gsub('I','𝕀')
Khaled9= Khaled9:gsub('o','𝕆')
Khaled9= Khaled9:gsub('O','𝕆')
Khaled9= Khaled9:gsub('p','ℙ')
Khaled9= Khaled9:gsub('P','ℙ')
Khaled9= Khaled9:gsub('a','𝔸')
Khaled9= Khaled9:gsub('A','𝔸')
Khaled9= Khaled9:gsub('s','𝕊')
Khaled9= Khaled9:gsub('S','𝕊')
Khaled9= Khaled9:gsub('d','𝔻')
Khaled9= Khaled9:gsub('D','𝔻')
Khaled9= Khaled9:gsub('f','𝔽')
Khaled9= Khaled9:gsub('F','𝔽')
Khaled9= Khaled9:gsub('g','𝔾')
Khaled9= Khaled9:gsub('G','𝔾')
Khaled9= Khaled9:gsub('h','ℍ')
Khaled9= Khaled9:gsub('H','ℍ')
Khaled9= Khaled9:gsub('j','𝕁')
Khaled9= Khaled9:gsub('J','𝕁')
Khaled9= Khaled9:gsub('k','𝕂')
Khaled9= Khaled9:gsub('K','𝕂')
Khaled9= Khaled9:gsub('L','𝕃')
Khaled9= Khaled9:gsub('l','𝕃')
Khaled9= Khaled9:gsub('z','ℤ')
Khaled9= Khaled9:gsub('Z','ℤ')
Khaled9= Khaled9:gsub('x','𝕏')
Khaled9= Khaled9:gsub('X','𝕏')
Khaled9= Khaled9:gsub('c','ℂ')
Khaled9= Khaled9:gsub('C','ℂ')
Khaled9= Khaled9:gsub('v','𝕍')
Khaled9= Khaled9:gsub('V','𝕍')
Khaled9= Khaled9:gsub('b','𝔹')
Khaled9= Khaled9:gsub('B','𝔹')
Khaled9= Khaled9:gsub('n','ℕ')
Khaled9= Khaled9:gsub('N','ℕ')
Khaled9= Khaled9:gsub('m','𝕄')
Khaled9= Khaled9:gsub('M','𝕄')


local Text_Khaleda = "1- `"..Khaled..EmojeS[math.random(#EmojeS)]
.."`\n\n2- `"..Khaled2..EmojeS[math.random(#EmojeS)]
.."`\n\n3- `"..Khaled3..EmojeS[math.random(#EmojeS)]
.."`\n\n4- `"..Khaled4..EmojeS[math.random(#EmojeS)]
.."`\n\n5- `"..Khaled5..EmojeS[math.random(#EmojeS)]
.."`\n\n6- `"..Khaled6..EmojeS[math.random(#EmojeS)]
.."`\n\n7- `"..Khaled7..EmojeS[math.random(#EmojeS)]
.."`\n\n8- `"..Khaled8..Emoje[math.random(#Emoje)]
.."`\n\n9- `"..Khaled9..Emoje[math.random(#Emoje)]
.."`\n\n10- `"..Khaled5..Emoje[math.random(#Emoje)]
Text_Khaleda = Text_Khaleda.."`\n\n اضغط علـي الاسـم ليـتم النـسخ \n★"
sendMsg(msg.chat_id_,msg.id_,Text_Khaleda)
return false
end
end

end
local function TextRes(msg)

if msg.text and msg.type ~= "pv" and redis:get(matrex..":KhaledNow:"..msg.sender_user_id_) then
Text = msg.text
redis:del(matrex..":KhaledNow:"..msg.sender_user_id_)
if utf8.len(msg.text) > 300 then
sendMsg(msg.chat_id_,msg.id_," لا يمكنك زخرفه اكثر من 300 حرف \n  ارسل امر زخرفه وحاول مجددا بحروف اقل")    
return false
end
local EmojeS = {
' 𓁻',
' 𓏴  ',
' 𓏶 ',
' 𓏡',
' 𓏢', 
' 𓏣', 
' ☽‘',
' 𖠱²²', 
'▽', 
' 𖡛“', 
' 𖡚℡', 
' 𖡨', 
}

local Emoje = {
' ♕',
' 𖤍',
'˛𖤓',
' ཻ ☫',
' ♫ ',
' 𖠶 ',
' 𖠲',
' 𖡥',
'  ☬',
' 𖤐',
' 𓇼',
' ♘  '
}


local Khaled = Text:gsub('ض','ضِٰـِۢ')
Khaled = Khaled:gsub('ص','صِٰـِۢ')
Khaled = Khaled:gsub('ث','ثِٰـِۢ')
Khaled = Khaled:gsub('ق','قِٰـِۢ')
Khaled = Khaled:gsub('ف','فِٰ͒ـِۢ')
Khaled = Khaled:gsub('غ','غِٰـِۢ')
Khaled = Khaled:gsub('ع','عِٰـِۢ')
Khaled = Khaled:gsub('خ','خِٰ̐ـِۢ')
Khaled = Khaled:gsub('ح','حِٰـِۢ')
Khaled = Khaled:gsub('ج','جِٰـِۢ')
Khaled = Khaled:gsub('ش','شِٰـِۢ')
Khaled = Khaled:gsub('س','سِٰـِۢ')
Khaled = Khaled:gsub('ي','يِٰـِۢ')
Khaled = Khaled:gsub('ب','بِٰـِۢ')
Khaled = Khaled:gsub('ل','لِٰـِۢ')
Khaled = Khaled:gsub('ا','آ')
Khaled = Khaled:gsub('ت','تِٰـِۢ')
Khaled = Khaled:gsub('ن','نِٰـِۢ')
Khaled = Khaled:gsub('م','مِٰـِۢ')
Khaled = Khaled:gsub('ك','ڪِٰـِۢ')
Khaled = Khaled:gsub('ط','طِٰـِۢ')
Khaled = Khaled:gsub('ظ','ظِٰـِۢ')
Khaled = Khaled:gsub('ء','ء')
Khaled = Khaled:gsub('ؤ','ؤ')
Khaled = Khaled:gsub('ر','ر')
Khaled = Khaled:gsub('ى','ى')
Khaled = Khaled:gsub('ز','ز')
Khaled = Khaled:gsub('و','ﯛ̲୭')
Khaled = Khaled:gsub('ه','ۿۿہ')
Khaled = Khaled:gsub('a','𝗮')
Khaled = Khaled:gsub('A','𝗔')
Khaled = Khaled:gsub("b","𝗯")
Khaled = Khaled:gsub("B","𝗕")
Khaled = Khaled:gsub("c","𝗰")
Khaled = Khaled:gsub("C","𝗖")
Khaled = Khaled:gsub("d","𝗱")
Khaled = Khaled:gsub("D","𝗗")
Khaled = Khaled:gsub("e","𝗲")
Khaled = Khaled:gsub("E","𝗘")
Khaled = Khaled:gsub("f","𝗳")
Khaled = Khaled:gsub("F","𝗙")
Khaled = Khaled:gsub("g","𝗴")
Khaled = Khaled:gsub("G","𝗚")
Khaled = Khaled:gsub("h","𝗵")
Khaled = Khaled:gsub("H","𝗛")
Khaled = Khaled:gsub("i","𝗹")
Khaled = Khaled:gsub("I","𝗜")
Khaled = Khaled:gsub("j","𝗝")
Khaled = Khaled:gsub("J","𝗝")
Khaled = Khaled:gsub("k","𝗸")
Khaled = Khaled:gsub("K","𝗞")
Khaled = Khaled:gsub("l","𝗹")
Khaled = Khaled:gsub("L","𝗟")
Khaled = Khaled:gsub("m","𝗺")
Khaled = Khaled:gsub("M","𝗠")
Khaled = Khaled:gsub("n","𝗻")
Khaled = Khaled:gsub("N","𝗡")
Khaled = Khaled:gsub("o","𝗼")
Khaled = Khaled:gsub("O","𝗢")
Khaled = Khaled:gsub("p","𝗽")
Khaled = Khaled:gsub("P","𝗣")
Khaled = Khaled:gsub("q","𝗾")
Khaled = Khaled:gsub("Q","𝗤")
Khaled = Khaled:gsub("r","𝗿")
Khaled = Khaled:gsub("R","𝗥")
Khaled = Khaled:gsub("s","𝘀")
Khaled = Khaled:gsub("S","𝗦")
Khaled = Khaled:gsub("t","𝘁")
Khaled = Khaled:gsub("T","𝗧")
Khaled = Khaled:gsub("u","𝘂")
Khaled = Khaled:gsub("U","𝗨")
Khaled = Khaled:gsub("v","𝘃")
Khaled = Khaled:gsub("V","𝗩")
Khaled = Khaled:gsub("w","𝘄")
Khaled = Khaled:gsub("W","𝗪")
Khaled = Khaled:gsub("x","𝘅")
Khaled = Khaled:gsub("X","𝗫")
Khaled = Khaled:gsub("y","𝘆")
Khaled = Khaled:gsub("Y","𝗬")
Khaled = Khaled:gsub("z","𝘇")
Khaled = Khaled:gsub("Z","𝗭")



local Khaled2 = Text:gsub('ض','ضَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ص','صَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ث','ثَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ق','قَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ف','فَٰ͒ـُـٰٓ')
Khaled2 = Khaled2:gsub('غ','غَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ع','عَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('خ','خَٰ̐ـُـٰٓ')
Khaled2 = Khaled2:gsub('ح','حَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ج','جَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ش','شَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('س','سَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ي','يَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ب','بَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ل','لَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ا','آ')
Khaled2 = Khaled2:gsub('ت','تَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ن','نَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('م','مَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ك','ڪَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ط','طَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ظ','ظَٰـُـٰٓ')
Khaled2 = Khaled2:gsub('ء','ء')
Khaled2 = Khaled2:gsub('ؤ','ؤ')
Khaled2 = Khaled2:gsub('ر','ر')
Khaled2 = Khaled2:gsub('ى','ى')
Khaled2 = Khaled2:gsub('ز','ز')
Khaled2 = Khaled2:gsub('و','ﯛ̲୭')
Khaled2 = Khaled2:gsub("ه", "ۿۿہ")
Khaled2 = Khaled2:gsub('a',"𝖆")
Khaled2 = Khaled2:gsub('A',"𝖆")
Khaled2 = Khaled2:gsub("b","𝖇")
Khaled2 = Khaled2:gsub("B","𝖇")
Khaled2 = Khaled2:gsub("c","𝖈")
Khaled2 = Khaled2:gsub("C","𝖈")
Khaled2 = Khaled2:gsub("d","𝖉")
Khaled2 = Khaled2:gsub("D","𝖉")
Khaled2 = Khaled2:gsub("e","𝖊")
Khaled2 = Khaled2:gsub("E","𝖊")
Khaled2 = Khaled2:gsub("f","𝖋")
Khaled2 = Khaled2:gsub("F","𝖋")
Khaled2 = Khaled2:gsub("g","𝖌")
Khaled2 = Khaled2:gsub("G","𝖌")
Khaled2 = Khaled2:gsub("h","𝖍")
Khaled2 = Khaled2:gsub("H","𝖍")
Khaled2 = Khaled2:gsub("i","𝖎")
Khaled2 = Khaled2:gsub("I","𝖎")
Khaled2 = Khaled2:gsub("j","𝖏")
Khaled2 = Khaled2:gsub("J","𝖏")
Khaled2 = Khaled2:gsub("k","𝖐")
Khaled2 = Khaled2:gsub("K","𝖐")
Khaled2 = Khaled2:gsub("l","𝖑")
Khaled2 = Khaled2:gsub("L","𝖑")
Khaled2 = Khaled2:gsub("m","𝖒")
Khaled2 = Khaled2:gsub("M","𝖒")
Khaled2 = Khaled2:gsub("n","𝖓")
Khaled2 = Khaled2:gsub("N","𝖓")
Khaled2 = Khaled2:gsub("o","𝖔")
Khaled2 = Khaled2:gsub("O","𝖔")
Khaled2 = Khaled2:gsub("p","𝖕")
Khaled2 = Khaled2:gsub("P","𝖕")
Khaled2 = Khaled2:gsub("q","𝖖")
Khaled2 = Khaled2:gsub("Q","𝖖")
Khaled2 = Khaled2:gsub("r","𝖗")
Khaled2 = Khaled2:gsub("R","𝖗")
Khaled2 = Khaled2:gsub("s","𝖘")
Khaled2 = Khaled2:gsub("S","𝖘")
Khaled2 = Khaled2:gsub("t","𝖙")
Khaled2 = Khaled2:gsub("T","𝖙")
Khaled2 = Khaled2:gsub("u","𝖚")
Khaled2 = Khaled2:gsub("U","𝖚")
Khaled2 = Khaled2:gsub("v","𝖛")
Khaled2 = Khaled2:gsub("V","𝖛")
Khaled2 = Khaled2:gsub("w","𝖜")
Khaled2 = Khaled2:gsub("W","𝖜")
Khaled2 = Khaled2:gsub("x","𝖝")
Khaled2 = Khaled2:gsub("X","𝖝")
Khaled2 = Khaled2:gsub("y","𝖞")
Khaled2 = Khaled2:gsub("Y","𝖞")
Khaled2 = Khaled2:gsub("z","𝖟")
Khaled2 = Khaled2:gsub("Z","𝖟")


local Khaled3= Text:gsub('ض','ض')
Khaled3= Khaled3:gsub('ص','ص')
Khaled3= Khaled3:gsub('ث','ثہ')
Khaled3= Khaled3:gsub('ق','ق')
Khaled3= Khaled3:gsub('ف','فُہ')
Khaled3= Khaled3:gsub('غ','غہ')
Khaled3= Khaled3:gsub('ع','عہ')
Khaled3= Khaled3:gsub('ه','هٰہٰٖ')
Khaled3= Khaled3:gsub('خ','خہ')
Khaled3= Khaled3:gsub('ح','حہ')
Khaled3= Khaled3:gsub('ج','جہ')
Khaled3= Khaled3:gsub('د','د')
Khaled3= Khaled3:gsub('ذ','ذ')
Khaled3= Khaled3:gsub('ش','شہ')
Khaled3= Khaled3:gsub('س','سہ')
Khaled3= Khaled3:gsub('ي','يہ')
Khaled3= Khaled3:gsub('ب','بّ')
Khaled3= Khaled3:gsub('ل','لہ')
Khaled3= Khaled3:gsub('ا','ا')
Khaled3= Khaled3:gsub('ت','تہ')
Khaled3= Khaled3:gsub('ن','نٰہٰٖ')
Khaled3= Khaled3:gsub('م','مٰہٰٖ')
Khaled3= Khaled3:gsub('ك','كُہ')
Khaled3= Khaled3:gsub('ط','طہ')
Khaled3= Khaled3:gsub('ئ','ئ ْٰ')
Khaled3= Khaled3:gsub('ء','ء')
Khaled3= Khaled3:gsub('ؤ','ؤ')
Khaled3= Khaled3:gsub('ر','رَ')
Khaled3= Khaled3:gsub('لا','لہا')
Khaled3= Khaled3:gsub('ى','ىْ')
Khaled3= Khaled3:gsub('ة','ة')
Khaled3= Khaled3:gsub('و','و')
Khaled3= Khaled3:gsub('ز','ز')
Khaled3= Khaled3:gsub('ظ','ظۗہٰٰ')
Khaled3= Khaled3:gsub('q','𝐪')
Khaled3= Khaled3:gsub('Q','𝐪')
Khaled3= Khaled3:gsub('w','𝐰')
Khaled3= Khaled3:gsub('W','𝐰')
Khaled3= Khaled3:gsub('e','𝐞')
Khaled3= Khaled3:gsub('E','𝐞')
Khaled3= Khaled3:gsub('r','𝐫')
Khaled3= Khaled3:gsub('R','𝐫')
Khaled3= Khaled3:gsub('t','𝐭')
Khaled3= Khaled3:gsub('T','𝐭')
Khaled3= Khaled3:gsub('y','𝐲')
Khaled3= Khaled3:gsub('Y','𝐲')
Khaled3= Khaled3:gsub('u','𝐮')
Khaled3= Khaled3:gsub('i','𝐢')
Khaled3= Khaled3:gsub('o','𝐨')
Khaled3= Khaled3:gsub('p','𝐩')
Khaled3= Khaled3:gsub('a','𝐚')
Khaled3= Khaled3:gsub('s','𝐬')
Khaled3= Khaled3:gsub('d','𝐝')
Khaled3= Khaled3:gsub('f','𝐟')
Khaled3= Khaled3:gsub('g','𝐠')
Khaled3= Khaled3:gsub('h','𝐡')
Khaled3= Khaled3:gsub('j','𝐣')
Khaled3= Khaled3:gsub('k','𝐤')
Khaled3= Khaled3:gsub('U','𝐮')
Khaled3= Khaled3:gsub('I','𝐢')
Khaled3= Khaled3:gsub('O','𝐨')
Khaled3= Khaled3:gsub('P','𝐩')
Khaled3= Khaled3:gsub('A','𝐚')
Khaled3= Khaled3:gsub('S','𝐬')
Khaled3= Khaled3:gsub('D','𝐝')
Khaled3= Khaled3:gsub('F','𝐟')
Khaled3= Khaled3:gsub('G','𝐠')
Khaled3= Khaled3:gsub('H','𝐡')
Khaled3= Khaled3:gsub('J','𝐣')
Khaled3= Khaled3:gsub('K','𝐤')
Khaled3= Khaled3:gsub('L','𝐥')
Khaled3= Khaled3:gsub('l','𝐥')
Khaled3= Khaled3:gsub('z','𝐳')
Khaled3= Khaled3:gsub('Z','𝐳')
Khaled3= Khaled3:gsub('x','𝐱')
Khaled3= Khaled3:gsub('X','ẋ')
Khaled3= Khaled3:gsub('c','𝐜')
Khaled3= Khaled3:gsub('C','𝐜')
Khaled3= Khaled3:gsub('v','𝐯')
Khaled3= Khaled3:gsub('V','𝐯')
Khaled3= Khaled3:gsub('b','𝐛')
Khaled3= Khaled3:gsub('B','𝐛')
Khaled3= Khaled3:gsub('n','𝐧')
Khaled3= Khaled3:gsub('N','𝐧')
Khaled3= Khaled3:gsub('m','𝐦')
Khaled3= Khaled3:gsub('M','𝐦')


local Khaled4= Text:gsub('ض','ضۜہٰٰ')
Khaled4= Khaled4:gsub('ص','ضۜہٰٰ')
Khaled4= Khaled4:gsub('ث','ثہٰٰ')
Khaled4= Khaled4:gsub('ق','قྀ̲ہٰٰ')
Khaled4= Khaled4:gsub('ف','ف͒ہٰٰ')
Khaled4= Khaled4:gsub('غ','غہٰٰ')
Khaled4= Khaled4:gsub('ع','عہٰٰ')
Khaled4= Khaled4:gsub('ه','هٰہٰٖ')
Khaled4= Khaled4:gsub('خ','خٰ̐ہ ')
Khaled4= Khaled4:gsub('ح','حہٰٰ')
Khaled4= Khaled4:gsub('ج','جـٰ̲ـہْۧ')
Khaled4= Khaled4:gsub('د','دٰ')
Khaled4= Khaled4:gsub('ذ','ذِٰ')
Khaled4= Khaled4:gsub('ش','شِٰہٰٰ')
Khaled4= Khaled4:gsub('س','سٰٓ')
Khaled4= Khaled4:gsub('ي','يِٰہ')
Khaled4= Khaled4:gsub('ب','بّہ')
Khaled4= Khaled4:gsub('ل','لـٰ̲ـہ')
Khaled4= Khaled4:gsub('ا','آ')
Khaled4= Khaled4:gsub('ت','تَہَٰ')
Khaled4= Khaled4:gsub('ن','نَِہ')
Khaled4= Khaled4:gsub('م','مٰ̲ہ')
Khaled4= Khaled4:gsub('ك','ڪٰྀہٰٰ')
Khaled4= Khaled4:gsub('ط','طۨہٰٰ')
Khaled4= Khaled4:gsub('ئ','ئ ْٰ')
Khaled4= Khaled4:gsub('ء','ء')
Khaled4= Khaled4:gsub('ؤ','ؤ')
Khaled4= Khaled4:gsub('ر','رَ')
Khaled4= Khaled4:gsub('لا','لہا')
Khaled4= Khaled4:gsub('ى','ىْ')
Khaled4= Khaled4:gsub('ة','ة')
Khaled4= Khaled4:gsub('و','وِٰ')
Khaled4= Khaled4:gsub('ز','زَٰ')
Khaled4= Khaled4:gsub('ظ','ظۗہٰٰ')
Khaled4= Khaled4:gsub('q','𝑸')
Khaled4= Khaled4:gsub('Q','𝑸')
Khaled4= Khaled4:gsub('w','𝑾')
Khaled4= Khaled4:gsub('W','𝑾')
Khaled4= Khaled4:gsub('e','𝑬')
Khaled4= Khaled4:gsub('E','𝑬')
Khaled4= Khaled4:gsub('r','𝑹')
Khaled4= Khaled4:gsub('R','𝑹')
Khaled4= Khaled4:gsub('t','𝑻')
Khaled4= Khaled4:gsub('T','𝑻')
Khaled4= Khaled4:gsub('y','𝒀')
Khaled4= Khaled4:gsub('Y','𝒀')
Khaled4= Khaled4:gsub('u','𝑼')
Khaled4= Khaled4:gsub('U','𝑼')
Khaled4= Khaled4:gsub('i','𝑰')
Khaled4= Khaled4:gsub('I','𝑰')
Khaled4= Khaled4:gsub('o','𝑶')
Khaled4= Khaled4:gsub('O','𝑶')
Khaled4= Khaled4:gsub('p','𝑷')
Khaled4= Khaled4:gsub('P','𝑷')
Khaled4= Khaled4:gsub('a','𝑨')
Khaled4= Khaled4:gsub('A','𝑨')
Khaled4= Khaled4:gsub('s','𝑺')
Khaled4= Khaled4:gsub('S','𝑺')
Khaled4= Khaled4:gsub('d','𝑫')
Khaled4= Khaled4:gsub('D','𝑫')
Khaled4= Khaled4:gsub('f','𝑭')
Khaled4= Khaled4:gsub('F','𝑭')
Khaled4= Khaled4:gsub('g','𝑮')
Khaled4= Khaled4:gsub('G','𝑮')
Khaled4= Khaled4:gsub('h','𝑯')
Khaled4= Khaled4:gsub('H','𝑯')
Khaled4= Khaled4:gsub('j','𝑱')
Khaled4= Khaled4:gsub('J','𝑱')
Khaled4= Khaled4:gsub('k','𝑲')
Khaled4= Khaled4:gsub('K','𝑲')
Khaled4= Khaled4:gsub('l','𝑳')
Khaled4= Khaled4:gsub('L','𝑳')
Khaled4= Khaled4:gsub('z','𝒁')
Khaled4= Khaled4:gsub('Z','𝒁')
Khaled4= Khaled4:gsub('x','𝑿')
Khaled4= Khaled4:gsub('X','𝑿')
Khaled4= Khaled4:gsub('c','𝑪')
Khaled4= Khaled4:gsub('C','𝑪')
Khaled4= Khaled4:gsub('v','𝑽')
Khaled4= Khaled4:gsub('V','𝑽')
Khaled4= Khaled4:gsub('b','𝑩')
Khaled4= Khaled4:gsub('B','𝑩')
Khaled4= Khaled4:gsub('n','𝑵')
Khaled4= Khaled4:gsub('N','𝑵')
Khaled4= Khaled4:gsub('m','𝑴')
Khaled4= Khaled4:gsub('M','𝑴')



local Khaled5= Text:gsub('ض','ضَ')
Khaled5= Khaled5:gsub('ص','صً')
Khaled5= Khaled5:gsub('ث','ثَ')
Khaled5= Khaled5:gsub('ق','قُ')
Khaled5= Khaled5:gsub('ف','فّ')
Khaled5= Khaled5:gsub('غ','غِ')
Khaled5= Khaled5:gsub('ع','عُ')
Khaled5= Khaled5:gsub('ه','ﮭ')
Khaled5= Khaled5:gsub('خ','خِ')
Khaled5= Khaled5:gsub('ح','حٌ')
Khaled5= Khaled5:gsub('ج','جُ')
Khaled5= Khaled5:gsub('د','دِ')
Khaled5= Khaled5:gsub('ذ','ذَ')
Khaled5= Khaled5:gsub('ش','شِ')
Khaled5= Khaled5:gsub('س','سً')
Khaled5= Khaled5:gsub('ي','يْ')
Khaled5= Khaled5:gsub('ب','بّ')
Khaled5= Khaled5:gsub('ل','لَ')
Khaled5= Khaled5:gsub('ا','أُ')
Khaled5= Khaled5:gsub('ت','تٌ')
Khaled5= Khaled5:gsub('ن','نً')
Khaled5= Khaled5:gsub('م','مِ')
Khaled5= Khaled5:gsub('ك','ڳّ')
Khaled5= Khaled5:gsub('ط','طٌ')
Khaled5= Khaled5:gsub('ئ','ئ')
Khaled5= Khaled5:gsub('ء','ء')
Khaled5= Khaled5:gsub('ؤ','ؤ')
Khaled5= Khaled5:gsub('ر','رٌ')
Khaled5= Khaled5:gsub('لا','لٌأً')
Khaled5= Khaled5:gsub('ى','ى')
Khaled5= Khaled5:gsub('ة','ةَ')
Khaled5= Khaled5:gsub('و','وِ')
Khaled5= Khaled5:gsub('ز','زُ')
Khaled5= Khaled5:gsub('ظ','ظ')
Khaled5= Khaled5:gsub('q','𝒒')
Khaled5= Khaled5:gsub('Q','𝒒')
Khaled5= Khaled5:gsub('w','𝒘')
Khaled5= Khaled5:gsub('W','𝒘')
Khaled5= Khaled5:gsub('e','𝒆')
Khaled5= Khaled5:gsub('E','𝒆')
Khaled5= Khaled5:gsub('r','𝒓')
Khaled5= Khaled5:gsub('R','𝒓')
Khaled5= Khaled5:gsub('t','𝒕')
Khaled5= Khaled5:gsub('T','𝒕')
Khaled5= Khaled5:gsub('y','𝒚')
Khaled5= Khaled5:gsub('Y','𝒚')
Khaled5= Khaled5:gsub('u','𝒖')
Khaled5= Khaled5:gsub('U','𝒖')
Khaled5= Khaled5:gsub('i','𝒊')
Khaled5= Khaled5:gsub('I','𝒊')
Khaled5= Khaled5:gsub('o','𝒐')
Khaled5= Khaled5:gsub('O','𝒐')
Khaled5= Khaled5:gsub('p','𝒑')
Khaled5= Khaled5:gsub('P','𝒑')
Khaled5= Khaled5:gsub('a','𝒂')
Khaled5= Khaled5:gsub('A','𝒂')
Khaled5= Khaled5:gsub('s','𝒔')
Khaled5= Khaled5:gsub('S','𝒔')
Khaled5= Khaled5:gsub('d','𝒅')
Khaled5= Khaled5:gsub('D','𝒅')
Khaled5= Khaled5:gsub('f','𝒇')
Khaled5= Khaled5:gsub('F','𝒇')
Khaled5= Khaled5:gsub('g','𝒈')
Khaled5= Khaled5:gsub('G','𝒈')
Khaled5= Khaled5:gsub('h','𝒉')
Khaled5= Khaled5:gsub('H','𝒉')
Khaled5= Khaled5:gsub('j','𝒋')
Khaled5= Khaled5:gsub('J','𝒋')
Khaled5= Khaled5:gsub('K','𝒌')
Khaled5= Khaled5:gsub('k','𝒌')
Khaled5= Khaled5:gsub('L','𝒍')
Khaled5= Khaled5:gsub('l','𝒍')
Khaled5= Khaled5:gsub('z','𝒛')
Khaled5= Khaled5:gsub('Z','𝒛')
Khaled5= Khaled5:gsub('x','𝒙')
Khaled5= Khaled5:gsub('X','𝒙')
Khaled5= Khaled5:gsub('c','𝒄')
Khaled5= Khaled5:gsub('C','𝒄')
Khaled5= Khaled5:gsub('v','𝒗')
Khaled5= Khaled5:gsub('V','𝒗')
Khaled5= Khaled5:gsub('b','𝒃')
Khaled5= Khaled5:gsub('B','𝒃')
Khaled5= Khaled5:gsub('n','𝒏')
Khaled5= Khaled5:gsub('N','𝒏')
Khaled5= Khaled5:gsub('m','𝒎')
Khaled5= Khaled5:gsub('M','𝒎')



local Khaled6= Text:gsub('ض','ﺿ̭͠')
Khaled6= Khaled6:gsub('ص','ﺻ͡')
Khaled6= Khaled6:gsub('ث','ﺜ̲')
Khaled6= Khaled6:gsub('ق','ﭰ')
Khaled6= Khaled6:gsub('ف','ﻓ̲')
Khaled6= Khaled6:gsub('غ','ﻏ̲')
Khaled6= Khaled6:gsub('ع','ﻌ̲')
Khaled6= Khaled6:gsub('ه','ﮬ̲̌')
Khaled6= Khaled6:gsub('خ','خٌ')
Khaled6= Khaled6:gsub('ح','ﺣ̅')
Khaled6= Khaled6:gsub('ج','جُ')
Khaled6= Khaled6:gsub('د','ډ̝')
Khaled6= Khaled6:gsub('ذ','ذً')
Khaled6= Khaled6:gsub('ش','ﺷ̲')
Khaled6= Khaled6:gsub('س','ﺳ̉')
Khaled6= Khaled6:gsub('ي','ﯾ̃̐')
Khaled6= Khaled6:gsub('ب','ﺑ̲')
Khaled6= Khaled6:gsub('ل','ا̄ﻟ')
Khaled6= Khaled6:gsub('ا','ﺈ̃')
Khaled6= Khaled6:gsub('ت','ټُ')
Khaled6= Khaled6:gsub('ن','ﻧ̲')
Khaled6= Khaled6:gsub('م','ﻣ̲̉')
Khaled6= Khaled6:gsub('ك','گ')
Khaled6= Khaled6:gsub('ط','ﻁ̲')
Khaled6= Khaled6:gsub('ئ',' ْٰئ')
Khaled6= Khaled6:gsub('ء','ء')
Khaled6= Khaled6:gsub('ؤ','ؤ')
Khaled6= Khaled6:gsub('ر','ہڕ')
Khaled6= Khaled6:gsub('لا','ﻟ̲ﺂ̲')
Khaled6= Khaled6:gsub('ى','ى')
Khaled6= Khaled6:gsub('ة','ة')
Khaled6= Khaled6:gsub('و','ۇۈۉ')
Khaled6= Khaled6:gsub('ز','زُ')
Khaled6= Khaled6:gsub('ظ','ﻇ̲')
Khaled6= Khaled6:gsub('q','ǫ')
Khaled6= Khaled6:gsub('Q','ǫ')
Khaled6= Khaled6:gsub('w','ᴡ')
Khaled6= Khaled6:gsub('W','ᴡ')
Khaled6= Khaled6:gsub('e','ᴇ')
Khaled6= Khaled6:gsub('E','ᴇ')
Khaled6= Khaled6:gsub('r','ʀ')
Khaled6= Khaled6:gsub('R','ʀ')
Khaled6= Khaled6:gsub('t','ᴛ')
Khaled6= Khaled6:gsub('T','ᴛ')
Khaled6= Khaled6:gsub('y','ʏ')
Khaled6= Khaled6:gsub('Y','ʏ')
Khaled6= Khaled6:gsub('u','ụ')
Khaled6= Khaled6:gsub('U','ụ')
Khaled6= Khaled6:gsub('i','ɪ')
Khaled6= Khaled6:gsub('I','ɪ')
Khaled6= Khaled6:gsub('o','ᴏ')
Khaled6= Khaled6:gsub('O','ᴏ')
Khaled6= Khaled6:gsub('p','ᴘ')
Khaled6= Khaled6:gsub('P','ᴘ')
Khaled6= Khaled6:gsub('a','ᴀ')
Khaled6= Khaled6:gsub('A','ᴀ')
Khaled6= Khaled6:gsub('s','ѕ')
Khaled6= Khaled6:gsub('S','ѕ')
Khaled6= Khaled6:gsub('d','ᴅ')
Khaled6= Khaled6:gsub('D','ᴅ')
Khaled6= Khaled6:gsub('f','ғ')
Khaled6= Khaled6:gsub('F','ғ')
Khaled6= Khaled6:gsub('g','ɢ')
Khaled6= Khaled6:gsub('G','ɢ')
Khaled6= Khaled6:gsub('h','ʜ')
Khaled6= Khaled6:gsub('H','ʜ')
Khaled6= Khaled6:gsub('j','ᴊ')
Khaled6= Khaled6:gsub('J','ᴊ')
Khaled6= Khaled6:gsub('K','ᴋ')
Khaled6= Khaled6:gsub('k','ᴋ')
Khaled6= Khaled6:gsub('L','ʟ')
Khaled6= Khaled6:gsub('l','ʟ')
Khaled6= Khaled6:gsub('z','ᴢ')
Khaled6= Khaled6:gsub('Z','ᴢ')
Khaled6= Khaled6:gsub('x','х')
Khaled6= Khaled6:gsub('X','х')
Khaled6= Khaled6:gsub('c','ᴄ')
Khaled6= Khaled6:gsub('C','ᴄ')
Khaled6= Khaled6:gsub('v','ᴠ')
Khaled6= Khaled6:gsub('V','ᴠ')
Khaled6= Khaled6:gsub('b','ʙ')
Khaled6= Khaled6:gsub('B','ʙ')
Khaled6= Khaled6:gsub('n','ɴ')
Khaled6= Khaled6:gsub('N','ɴ')
Khaled6= Khaled6:gsub('m','ᴍ')
Khaled6= Khaled6:gsub('M','ᴍ')



local Khaled7= Text:gsub('ض','ﺿ')
Khaled7= Khaled7:gsub('ص','ﺻ')
Khaled7= Khaled7:gsub('ث','ﭥ')
Khaled7= Khaled7:gsub('ق','ﻗ̮ـ̃')
Khaled7= Khaled7:gsub('ف','ﭬ')
Khaled7= Khaled7:gsub('غ','ﻏ̣̐')
Khaled7= Khaled7:gsub('ع','ﻋ')
Khaled7= Khaled7:gsub('ه','ھَہّ')
Khaled7= Khaled7:gsub('خ','ﺧ')
Khaled7= Khaled7:gsub('ح','פ')
Khaled7= Khaled7:gsub('ج','ﭴ')
Khaled7= Khaled7:gsub('د','ﮃ')
Khaled7= Khaled7:gsub('ذ','ذ')
Khaled7= Khaled7:gsub('ش','ﺷ')
Khaled7= Khaled7:gsub('س','ﺳ')
Khaled7= Khaled7:gsub('ي','ﯾ')
Khaled7= Khaled7:gsub('ب','ﺑ')
Khaled7= Khaled7:gsub('ل','ﻟ')
Khaled7= Khaled7:gsub('ا','ﺂ')
Khaled7= Khaled7:gsub('ت','ﭠ')
Khaled7= Khaled7:gsub('ن','ﻧ')
Khaled7= Khaled7:gsub('م','ﻣ̝̚')
Khaled7= Khaled7:gsub('ك','گـ')
Khaled7= Khaled7:gsub('ط','ﻁْ')
Khaled7= Khaled7:gsub('ئ','ٰئـ')
Khaled7= Khaled7:gsub('ء','ء')
Khaled7= Khaled7:gsub('ؤ','ﯗ')
Khaled7= Khaled7:gsub('ر','ړُ')
Khaled7= Khaled7:gsub('لا','ﻟآ')
Khaled7= Khaled7:gsub('ى','ـﮯ')
Khaled7= Khaled7:gsub('ة','ة')
Khaled7= Khaled7:gsub('و','ۆ')
Khaled7= Khaled7:gsub('ز','ژ')
Khaled7= Khaled7:gsub('ظ','ﻅ')
Khaled7= Khaled7:gsub('q','𝘘')
Khaled7= Khaled7:gsub('Q','𝘘')
Khaled7= Khaled7:gsub('w','𝘞')
Khaled7= Khaled7:gsub('W','𝘞')
Khaled7= Khaled7:gsub('e','𝘌')
Khaled7= Khaled7:gsub('E','𝘌')
Khaled7= Khaled7:gsub('r','𝘙')
Khaled7= Khaled7:gsub('R','𝘙')
Khaled7= Khaled7:gsub('t','𝘛')
Khaled7= Khaled7:gsub('T','𝘛')
Khaled7= Khaled7:gsub('y','𝘠')
Khaled7= Khaled7:gsub('Y','𝘠')
Khaled7= Khaled7:gsub('u','𝘜')
Khaled7= Khaled7:gsub('U','𝘜')
Khaled7= Khaled7:gsub('i','𝘐')
Khaled7= Khaled7:gsub('I','𝘐')
Khaled7= Khaled7:gsub('o','𝘖')
Khaled7= Khaled7:gsub('O','𝘖')
Khaled7= Khaled7:gsub('p','𝘗')
Khaled7= Khaled7:gsub('P','𝘗')
Khaled7= Khaled7:gsub('a','𝘈')
Khaled7= Khaled7:gsub('A','𝘈')
Khaled7= Khaled7:gsub('s','𝘚')
Khaled7= Khaled7:gsub('S','𝘚')
Khaled7= Khaled7:gsub('d','𝘋')
Khaled7= Khaled7:gsub('D','𝘋')
Khaled7= Khaled7:gsub('f','𝘍')
Khaled7= Khaled7:gsub('F','𝘍')
Khaled7= Khaled7:gsub('g','𝘎')
Khaled7= Khaled7:gsub('G','𝘎')
Khaled7= Khaled7:gsub('h','𝘏')
Khaled7= Khaled7:gsub('H','𝘏')
Khaled7= Khaled7:gsub('j','𝘑')
Khaled7= Khaled7:gsub('J','𝘑')
Khaled7= Khaled7:gsub('k','𝘒')
Khaled7= Khaled7:gsub('K','𝘒')
Khaled7= Khaled7:gsub('L','𝘓')
Khaled7= Khaled7:gsub('l','𝘓')
Khaled7= Khaled7:gsub('z','𝘡')
Khaled7= Khaled7:gsub('Z','𝘡')
Khaled7= Khaled7:gsub('x','𝘟')
Khaled7= Khaled7:gsub('X','𝘟')
Khaled7= Khaled7:gsub('c','𝘊')
Khaled7= Khaled7:gsub('C','𝘊')
Khaled7= Khaled7:gsub('v','𝘝')
Khaled7= Khaled7:gsub('V','𝘝')
Khaled7= Khaled7:gsub('b','𝘉')
Khaled7= Khaled7:gsub('B','𝘉')
Khaled7= Khaled7:gsub('n','𝘕')
Khaled7= Khaled7:gsub('N','𝘕')
Khaled7= Khaled7:gsub('m','𝘔')
Khaled7= Khaled7:gsub('M','𝘔')



local Khaled8= Text:gsub('ض','ض');
Khaled8= Khaled8:gsub('ص','صہٰ')
Khaled8= Khaled8:gsub('ث','ثہٰـ')
Khaled8= Khaled8:gsub('ق','قہٰ')
Khaled8= Khaled8:gsub('ف','فہٰ')
Khaled8= Khaled8:gsub('غ','غـْ')
Khaled8= Khaled8:gsub('ع','ع')
Khaled8= Khaled8:gsub('ه','هٰہٰٖ')
Khaled8= Khaled8:gsub('خ','خخَـ')
Khaled8= Khaled8:gsub('ح','حہٰ')
Khaled8= Khaled8:gsub('ج','ججہٰ')
Khaled8= Khaled8:gsub('د','دَ')
Khaled8= Khaled8:gsub('ذ','ذّ')
Khaled8= Khaled8:gsub('ش','ششہٰ')
Khaled8= Khaled8:gsub('س','سہٰ')
Khaled8= Khaled8:gsub('ي','يٰ')
Khaled8= Khaled8:gsub('ب','بٰٰ')
Khaled8= Khaled8:gsub('ل','لہٰ')
Khaled8= Khaled8:gsub('ا','آ')
Khaled8= Khaled8:gsub('ت','تہٰ')
Khaled8= Khaled8:gsub('ن','نہٰ')
Khaled8= Khaled8:gsub('م','مہٰ')
Khaled8= Khaled8:gsub('ك','ككہٰ')
Khaled8= Khaled8:gsub('ط','طہٰ')
Khaled8= Khaled8:gsub('ئ',' ْئٰ')
Khaled8= Khaled8:gsub('ء','ء')
Khaled8= Khaled8:gsub('ؤ','ؤؤَ')
Khaled8= Khaled8:gsub('ر','رَ')
Khaled8= Khaled8:gsub('لا','لہٰا')
Khaled8= Khaled8:gsub('ى','ىہٰ')
Khaled8= Khaled8:gsub('ة','ة')
Khaled8= Khaled8:gsub('و','ہٰو')
Khaled8= Khaled8:gsub('ز','ز')
Khaled8= Khaled8:gsub('ظ','ظہٰ')
Khaled8= Khaled8:gsub('q','𝚀')
Khaled8= Khaled8:gsub('Q','𝚀')
Khaled8= Khaled8:gsub('w','𝚆')
Khaled8= Khaled8:gsub('W','𝚆')
Khaled8= Khaled8:gsub('e','𝙴')
Khaled8= Khaled8:gsub('E','𝙴')
Khaled8= Khaled8:gsub('r','𝚁')
Khaled8= Khaled8:gsub('R','𝚁')
Khaled8= Khaled8:gsub('t','𝚃')
Khaled8= Khaled8:gsub('T','𝚃')
Khaled8= Khaled8:gsub('y','𝚈')
Khaled8= Khaled8:gsub('Y','𝚈')
Khaled8= Khaled8:gsub('u','𝚄')
Khaled8= Khaled8:gsub('U','𝚄')
Khaled8= Khaled8:gsub('i','𝙸')
Khaled8= Khaled8:gsub('I','𝙸')
Khaled8= Khaled8:gsub('o','𝙾')
Khaled8= Khaled8:gsub('O','𝙾')
Khaled8= Khaled8:gsub('p','𝙿')
Khaled8= Khaled8:gsub('P','𝙿')
Khaled8= Khaled8:gsub('a','𝙰')
Khaled8= Khaled8:gsub('A','𝙰')
Khaled8= Khaled8:gsub('s','𝚂')
Khaled8= Khaled8:gsub('S','𝚂')
Khaled8= Khaled8:gsub('d','𝙳')
Khaled8= Khaled8:gsub('D','𝙳')
Khaled8= Khaled8:gsub('f','𝙵')
Khaled8= Khaled8:gsub('F','𝙵')
Khaled8= Khaled8:gsub('g','𝙶')
Khaled8= Khaled8:gsub('G','𝙶')
Khaled8= Khaled8:gsub('h','𝙷')
Khaled8= Khaled8:gsub('H','𝙷')
Khaled8= Khaled8:gsub('j','𝙹')
Khaled8= Khaled8:gsub('J','𝙹')
Khaled8= Khaled8:gsub('k','𝙺')
Khaled8= Khaled8:gsub('K','𝙺')
Khaled8= Khaled8:gsub('L','𝙻')
Khaled8= Khaled8:gsub('l','𝙻')
Khaled8= Khaled8:gsub('z','𝚉')
Khaled8= Khaled8:gsub('Z','𝚉')
Khaled8= Khaled8:gsub('x','𝚇')
Khaled8= Khaled8:gsub('X','𝚇')
Khaled8= Khaled8:gsub('c','𝙲')
Khaled8= Khaled8:gsub('C','𝙲')
Khaled8= Khaled8:gsub('v','𝚅')
Khaled8= Khaled8:gsub('V','𝚅')
Khaled8= Khaled8:gsub('b','𝙱')
Khaled8= Khaled8:gsub('B','𝙱')
Khaled8= Khaled8:gsub('n','𝙽')
Khaled8= Khaled8:gsub('N','𝙽')
Khaled8= Khaled8:gsub('m','𝙼')
Khaled8= Khaled8:gsub('M','𝙼')



local Khaled9= Text:gsub('ض','ض')
Khaled9= Khaled9:gsub('ص','ص')
Khaled9= Khaled9:gsub('ث','ث')
Khaled9= Khaled9:gsub('ق','قٌ')
Khaled9= Khaled9:gsub('ف','فُ')
Khaled9= Khaled9:gsub('غ','غ')
Khaled9= Khaled9:gsub('ع','عٍ')
Khaled9= Khaled9:gsub('ه','هـ')
Khaled9= Khaled9:gsub('خ','خـ')
Khaled9= Khaled9:gsub('ح','حٍ')
Khaled9= Khaled9:gsub('ج','جٍ')
Khaled9= Khaled9:gsub('د','دِ')
Khaled9= Khaled9:gsub('ذ','ذَ')
Khaled9= Khaled9:gsub('ش','شُ')
Khaled9= Khaled9:gsub('س','س')
Khaled9= Khaled9:gsub('ي','ي')
Khaled9= Khaled9:gsub('ب','بَ')
Khaled9= Khaled9:gsub('ل','لُِ')
Khaled9= Khaled9:gsub('ا','آ')
Khaled9= Khaled9:gsub('ت','ت')
Khaled9= Khaled9:gsub('ن','ن')
Khaled9= Khaled9:gsub('م','م')
Khaled9= Khaled9:gsub('ك','ڪ')
Khaled9= Khaled9:gsub('ط','طُ')
Khaled9= Khaled9:gsub('ئ','ئ ْٰ')
Khaled9= Khaled9:gsub('ء','ء')
Khaled9= Khaled9:gsub('ؤ','ؤ')
Khaled9= Khaled9:gsub('ر','ر')
Khaled9= Khaled9:gsub('لا','لُِآ')
Khaled9= Khaled9:gsub('ى','ىْ')
Khaled9= Khaled9:gsub('ة','ة')
Khaled9= Khaled9:gsub('و','وو')
Khaled9= Khaled9:gsub('ز','ز')
Khaled9= Khaled9:gsub('ظ','ظهُ')
Khaled9= Khaled9:gsub('q','ℚ')
Khaled9= Khaled9:gsub('Q','ℚ')
Khaled9= Khaled9:gsub('w','𝕎')
Khaled9= Khaled9:gsub('W','𝕎')
Khaled9= Khaled9:gsub('e','𝔼')
Khaled9= Khaled9:gsub('E','𝔼')
Khaled9= Khaled9:gsub('r','ℝ')
Khaled9= Khaled9:gsub('R','ℝ')
Khaled9= Khaled9:gsub('t','𝕋')
Khaled9= Khaled9:gsub('T','𝕋')
Khaled9= Khaled9:gsub('y','𝕐')
Khaled9= Khaled9:gsub('Y','𝕐')
Khaled9= Khaled9:gsub('u','𝕌')
Khaled9= Khaled9:gsub('U','𝕌')
Khaled9= Khaled9:gsub('i','𝕀')
Khaled9= Khaled9:gsub('I','𝕀')
Khaled9= Khaled9:gsub('o','𝕆')
Khaled9= Khaled9:gsub('O','𝕆')
Khaled9= Khaled9:gsub('p','ℙ')
Khaled9= Khaled9:gsub('P','ℙ')
Khaled9= Khaled9:gsub('a','𝔸')
Khaled9= Khaled9:gsub('A','𝔸')
Khaled9= Khaled9:gsub('s','𝕊')
Khaled9= Khaled9:gsub('S','𝕊')
Khaled9= Khaled9:gsub('d','𝔻')
Khaled9= Khaled9:gsub('D','𝔻')
Khaled9= Khaled9:gsub('f','𝔽')
Khaled9= Khaled9:gsub('F','𝔽')
Khaled9= Khaled9:gsub('g','𝔾')
Khaled9= Khaled9:gsub('G','𝔾')
Khaled9= Khaled9:gsub('h','ℍ')
Khaled9= Khaled9:gsub('H','ℍ')
Khaled9= Khaled9:gsub('j','𝕁')
Khaled9= Khaled9:gsub('J','𝕁')
Khaled9= Khaled9:gsub('k','𝕂')
Khaled9= Khaled9:gsub('K','𝕂')
Khaled9= Khaled9:gsub('L','𝕃')
Khaled9= Khaled9:gsub('l','𝕃')
Khaled9= Khaled9:gsub('z','ℤ')
Khaled9= Khaled9:gsub('Z','ℤ')
Khaled9= Khaled9:gsub('x','𝕏')
Khaled9= Khaled9:gsub('X','𝕏')
Khaled9= Khaled9:gsub('c','ℂ')
Khaled9= Khaled9:gsub('C','ℂ')
Khaled9= Khaled9:gsub('v','𝕍')
Khaled9= Khaled9:gsub('V','𝕍')
Khaled9= Khaled9:gsub('b','𝔹')
Khaled9= Khaled9:gsub('B','𝔹')
Khaled9= Khaled9:gsub('n','ℕ')
Khaled9= Khaled9:gsub('N','ℕ')
Khaled9= Khaled9:gsub('m','𝕄')
Khaled9= Khaled9:gsub('M','𝕄')


local Text_Khaleda = "1- `"..Khaled..EmojeS[math.random(#EmojeS)]
.."`\n\n2- `"..Khaled2..EmojeS[math.random(#EmojeS)]
.."`\n\n3- `"..Khaled3..EmojeS[math.random(#EmojeS)]
.."`\n\n4- `"..Khaled4..EmojeS[math.random(#EmojeS)]
.."`\n\n5- `"..Khaled5..EmojeS[math.random(#EmojeS)]
.."`\n\n6- `"..Khaled6..EmojeS[math.random(#EmojeS)]
.."`\n\n7- `"..Khaled7..EmojeS[math.random(#EmojeS)]
.."`\n\n8- `"..Khaled8..Emoje[math.random(#Emoje)]
.."`\n\n9- `"..Khaled9..Emoje[math.random(#Emoje)]
.."`\n\n10- `"..Khaled5..Emoje[math.random(#Emoje)]
Text_Khaleda = Text_Khaleda.."`\n\n| اضغـط علـي الاسـم ليتـم النـسخ  \n★"
sendMsg(msg.chat_id_,msg.id_,Text_Khaleda)
return false
end



end

return {
matrex = {
"^(زخرفه)$"
 },
 imatrex = Khaleda,
 dmatrex = TextRes,
 }
 
 

--[[
DOX..🖤 ❍  @HH22H
│تم تطوير وبرمجة السورس من قبل التركي ✺
 @ SourceDOX
#-------------------------------------------------------------------
]]
